<a href="https://colab.research.google.com/github/aquisxd/Big_Data/blob/main/BIG_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Guía Práctica de NumPy


In [1]:
# Paso 1: Importar NumPy
import numpy as np

In [83]:
# Paso 2: Creación de Arrays
# Array unidimensional
vector = np.array([1,2,3,8,9,7])
# Matriz bidimensional 3x3 con valores enteros consecutivos
matriz = np.arange(1, 10).reshape(3, 3)
# Matriz 2x4 llena de ceros
zeros_matriz = np.zeros((2, 4))
# Matriz 3x2 llena de unos
ones_matriz = np.ones((3, 2))
# Matriz 4x4 con números enteros aleatorios entre 0 y 10
random_matriz = np.random.randint(0, 11, (4, 4))

print("El matriz dimencional es ",vector)
print("La matriz 3x3 es",matriz)
print("La matriz 2x4 es", zeros_matriz)
print("La matriz 3x2 es",ones_matriz)
print("La matriz 4x4 es",random_matriz)

El matriz dimencional es  [1 2 3 8 9 7]
La matriz 3x3 es [[1 2 3]
 [4 5 6]
 [7 8 9]]
La matriz 2x4 es [[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
La matriz 3x2 es [[1. 1.]
 [1. 1.]
 [1. 1.]]
La matriz 4x4 es [[ 8 10  2  8]
 [ 9  4  2  2]
 [ 1  1  9  9]
 [ 3  4  2  5]]


In [57]:
# Paso 3: Acceso a Elementos
# Acceder al tercer elemento del vector
tercer_elemento = vector[2]
# Acceder al elemento en la segunda fila y segunda columna de la matriz
elemento_2_2 = matriz[1, 1]

print("El tercer elemento es",tercer_elemento)
print("El elemento de la segunda fila es",elemento_2_2)

El tercer elemento es 3
El elemento de la segunda fila es 5


In [90]:
# Paso 4: Propiedades de los Arrays
# Cantidad de dimensiones
ndim = matriz.ndim
# Forma de la matriz
shape = matriz.shape
# Tamaño total de la matriz
size = matriz.size
print("La cantidad de dimensiones es",matriz.ndim)
print("El tamaño total de la matriz es",matriz.shape)
print("Tamaño total de la matriz es", matriz.size)

La cantidad de dimensiones es 2
El tamaño total de la matriz es (3, 3)
Tamaño total de la matriz es 9


In [67]:
# Paso 5: Operaciones Básicas
# Suma de dos matrices 2x2
matriz_a = np.random.randint(0, 11, (2, 2))
matriz_b = np.random.randint(0, 11, (2, 2))
suma = matriz_a + matriz_b
# Multiplicación de matrices 3x2 y 2x3
matriz_c = np.random.randint(0, 11, (3, 2))
matriz_d = np.random.randint(0, 11, (2, 3))
multiplicacion = np.dot(matriz_c, matriz_d)
# División por elementos y multiplicación por la inversa
matriz_e = np.random.randint(1, 11, (2, 2))
matriz_f = np.random.randint(1, 11, (2, 2))
division_elementos = matriz_e / matriz_f
inversa_f = np.linalg.inv(matriz_f)
multiplicacion_inversa = np.dot(matriz_e, inversa_f)

print("La suma de dos matrices de 2x2 es ",suma)
print("la multiplicación de matrices 3x2 y 2x3 es ",multiplicacion)
print("La división por elementos y multiplición a la inversa es ",multiplicacion_inversa)


La suma de dos matrices de 2x2 es  [[13 12]
 [13  5]]
la multiplicación de matrices 3x2 y 2x3 es  [[18 24 50]
 [14 27 70]
 [ 7  6  7]]
La división por elementos y multiplición a la inversa es  [[-0.85245902  0.96721311]
 [ 0.19672131  0.62295082]]


In [82]:

# Paso 6: Manipulación de Arrays
# Convertir vector a matriz 2x3
vector_reshape = vector.reshape((2,3))
# Convertir matriz a vector unidimensional
matriz_flatten = matriz.flatten()

print("convertir vector", vector_reshape)

print("convertir matriz a vector", matriz_flatten)

convertir vector [[1 2 3]
 [8 9 7]]
convertir matriz a vector [1 2 3 4 5 6 7 8 9]


In [86]:
# Paso 7: Operaciones Estadísticas
# Suma de todos los elementos de la matriz
suma_elementos = np.sum(matriz)
# Media de cada fila de la matriz
media_filas = np.mean(matriz, axis=1)
print("La suma de todos los elementos de la matriz es",suma_elementos)
print("La media de cada fila es", media_filas)

La suma de todos los elementos de la matriz es 45
La media de cada fila es [2. 5. 8.]


In [89]:
# Paso 8: Indexación y Rebanado
# Primera fila de la matriz
primera_fila = matriz[0, :]
# Primeras dos columnas de la matriz
primeras_dos_columnas = matriz[:, :2]

print("La primera fila de la matriz es:", primera_fila)
print("Las primeras dos culumnas de la matriz es:", primeras_dos_columnas)

La primera fila de la matriz es: [1 2 3]
Las primeras dos culumnas de la matriz es: [[1 2]
 [4 5]
 [7 8]]


In [29]:
# Paso 9: Ejercicio Adicional
# Matriz 4x4 con valores aleatorios
matriz_4x4 = np.random.rand(4, 4)
# Valor máximo, mínimo y sus posiciones
valor_maximo = matriz_4x4.max()
posicion_maximo = np.unravel_index(np.argmax(matriz_4x4), matriz_4x4.shape)
valor_minimo = matriz_4x4.min()
posicion_minimo = np.unravel_index(np.argmin(matriz_4x4), matriz_4x4.shape)

# Imprimir resultados para verificar
print("Matriz 4x4 con valores aleatorios:\n", matriz_4x4)
print("Valor máximo:", valor_maximo, "en posición", posicion_maximo)
print("Valor mínimo:", valor_minimo, "en posición", posicion_minimo)

Matriz 4x4 con valores aleatorios:
 [[0.16281427 0.307154   0.68428126 0.49790427]
 [0.47188605 0.41259152 0.8028986  0.51605141]
 [0.61178637 0.46707002 0.82072951 0.34822283]
 [0.46243906 0.66913685 0.06681242 0.23276387]]
Valor máximo: 0.8207295077363925 en posición (2, 2)
Valor mínimo: 0.06681241680461514 en posición (3, 2)
